### PR TITLE
Modified the alignment of rollno.

### PR DESCRIPTION
**Pull request by Harshs0891**
rollno

### CODE REVIEW

**Comment by superiorsd10** [comment]
@Harshs0891 thanks for the PR! But first, mention the issue number in the PR description, and describe how you solved the issue. Then I'll merge it, and will give you points for this.

**Comment by Harshs0891** [comment]
sir this was issue no. #8 
I just used MainAxisAlignment to spaceAround so the words in container are evenly spaced

**Comment by superiorsd10** [comment]
@Harshs0891 I'm merging it. You can write this in the PR description as well by editing it. There is an edit button there on clicking those three dots.

**Comment by superiorsd10** [comment]
@Harshs0891 Also you should make a new branch from the main for each issue.

**Comment by Harshs0891** [comment]
okay sir thank you

**Pull request merged**
